version : '3'

services:

  nginx:
    container_name: "${COMPOSE_PROJECT_NAME}_nginx"
    command: "bash /entrypoint.sh"
    image: "${NGINX_IMAGE}"
    volumes:
      - "./compose/nginx/entrypoint.sh:/entrypoint.sh"
      - "./${SRC_DIR}:/var/www/${COMPOSE_PROJECT_NAME}"
      - "./compose/nginx/conf:/etc/nginx/conf.d.template"
      - "./compose/nginx/ssl:/etc/nginx/ssl"
      - "./shared/nginx/logs:/var/log/nginx"
    ports:
      - "80:80"
      - "443:443"
    links:
      - "php"
    environment:
      - COMPOSE_PROJECT_NAME
      - SRC_DOCUMENT_ROOT
      - PHP_APP_ENTRYPOINT
